Car Price Prediction::

Download dataset from this link:

https://www.kaggle.com/hellbuoy/car-price-prediction

Problem Statement::Â¶

A Chinese automobile company Geely Auto aspires to enter the US market by setting up their manufacturing unit there and producing cars locally to give competition to their US and European counterparts.

They have contracted an automobile consulting company to understand the factors on which the pricing of cars depends. Specifically, they want to understand the factors affecting the pricing of cars in the American market, since those may be very different from the Chinese market. The company wants to know:

Which variables are significant in predicting the price of a car How well those variables describe the price of a car Based on various market surveys, the consulting firm has gathered a large data set of different types of cars across the America market.

task::
We are required to model the price of cars with the available independent variables. It will be used by the management to understand how exactly the prices vary with the independent variables. They can accordingly manipulate the design of the cars, the business strategy etc. to meet certain price levels. Further, the model will be a good way for management to understand the pricing dynamics of a new market.

WORKFLOW ::

1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

4.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

5.Compilation Step (Note : Its a Regression problem , select loss , metrics according to it) 6.Train the Model with Epochs (100) and validate it

7.If the model gets overfit tune your model by changing the units , No. of layers , activation function , epochs , add dropout layer or add Regularizer according to the need .

8.Evaluation Step

9.Prediction

In [ ]:
import pandas as pd
import numpy as np
car_data = pd.read_csv("./drive/MyDrive/Dl_Assignments/DLAssignments/CarPrice_Assignment.csv")

In [ ]:
import tensorflow as tf

In [ ]:
car_data

     car_ID  symboling                   CarName  ... citympg highwaympg    price
0         1          3        alfa-romero giulia  ...      21         27  13495.0
1         2          3       alfa-romero stelvio  ...      21         27  16500.0
2         3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3         4          2               audi 100 ls  ...      24         30  13950.0
4         5          2                audi 100ls  ...      18         22  17450.0
..      ...        ...                       ...  ...     ...        ...      ...
200     201         -1           volvo 145e (sw)  ...      23         28  16845.0
201     202         -1               volvo 144ea  ...      19         25  19045.0
202     203         -1               volvo 244dl  ...      18         23  21485.0
203     204         -1                 volvo 246  ...      26         27  22470.0
204     205         -1               volvo 264gl  ...      19         25  22625.0

[205 rows x 26 columns]

In [ ]:
#car_data.drop(columns=["car_ID"], inplace=True)

In [ ]:
#car_data.columns

Index(['symboling', 'CarName', 'fueltype', 'aspiration', 'doornumber',
       'carbody', 'drivewheel', 'enginelocation', 'wheelbase', 'carlength',
       'carwidth', 'carheight', 'curbweight', 'enginetype', 'cylindernumber',
       'enginesize', 'fuelsystem', 'boreratio', 'stroke', 'compressionratio',
       'horsepower', 'peakrpm', 'citympg', 'highwaympg', 'price'],
      dtype='object')

In [ ]:
car_data.drop(columns = ['car_ID'], inplace= True)

In [ ]:
final_car = pd.get_dummies(car_data, columns=['symboling','CarName','fueltype',	'aspiration',	'doornumber',	'carbody',	'drivewheel',	'enginelocation',	'enginetype',	'cylindernumber',	'fuelsystem'])

In [ ]:
np.where(final_car.applymap(lambda x: x ==''))

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
final_car.describe()

        wheelbase   carlength  ...  fuelsystem_spdi  fuelsystem_spfi
count  205.000000  205.000000  ...       205.000000       205.000000
mean    98.756585  174.049268  ...         0.043902         0.004878
std      6.021776   12.337289  ...         0.205380         0.069843
min     86.600000  141.100000  ...         0.000000         0.000000
25%     94.500000  166.300000  ...         0.000000         0.000000
50%     97.000000  173.200000  ...         0.000000         0.000000
75%    102.400000  183.100000  ...         0.000000         0.000000
max    120.900000  208.100000  ...         1.000000         1.000000

[8 rows x 205 columns]

In [ ]:
np.random.seed(11111)
msk = np.random.rand(len(final_car)) < 0.72
train_total = final_car[msk]
test_total = final_car[~msk]

In [ ]:
print(len(train_total))
print(len(test_total))

141
64

In [ ]:
test_data= test_total.drop(columns = ['price'])
train_data= train_total.drop(columns = ['price'])

In [ ]:
train_label = train_total.loc[:,'price']
test_label = test_total.loc[:,'price']

In [ ]:
{train_data.columns.get_loc(c): c for idx, c in enumerate(train_data.columns)}

{0: 'wheelbase',
 1: 'carlength',
 2: 'carwidth',
 3: 'carheight',
 4: 'curbweight',
 5: 'enginesize',
 6: 'boreratio',
 7: 'stroke',
 8: 'compressionratio',
 9: 'horsepower',
 10: 'peakrpm',
 11: 'citympg',
 12: 'highwaympg',
 13: 'symboling_-2',
 14: 'symboling_-1',
 15: 'symboling_0',
 16: 'symboling_1',
 17: 'symboling_2',
 18: 'symboling_3',
 19: 'CarName_Nissan versa',
 20: 'CarName_alfa-romero Quadrifoglio',
 21: 'CarName_alfa-romero giulia',
 22: 'CarName_alfa-romero stelvio',
 23: 'CarName_audi 100 ls',
 24: 'CarName_audi 100ls',
 25: 'CarName_audi 4000',
 26: 'CarName_audi 5000',
 27: 'CarName_audi 5000s (diesel)',
 28: 'CarName_audi fox',
 29: 'CarName_bmw 320i',
 30: 'CarName_bmw x1',
 31: 'CarName_bmw x3',
 32: 'CarName_bmw x4',
 33: 'CarName_bmw x5',
 34: 'CarName_bmw z4',
 35: 'CarName_buick century',
 36: 'CarName_buick century luxus (sw)',
 37: 'CarName_buick century special',
 38: 'CarName_buick electra 225 custom',
 39: 'CarName_buick opel isuzu deluxe',
 40: 'CarName_buick regal sport coupe (turbo)',
 41: 'CarName_buick skyhawk',
 42: 'CarName_buick skylark',
 43: 'CarName_chevrolet impala',
 44: 'CarName_chevrolet monte carlo',
 45: 'CarName_chevrolet vega 2300',
 46: 'CarName_dodge challenger se',
 47: 'CarName_dodge colt (sw)',
 48: 'CarName_dodge colt hardtop',
 49: 'CarName_dodge coronet custom',
 50: 'CarName_dodge coronet custom (sw)',
 51: 'CarName_dodge d200',
 52: 'CarName_dodge dart custom',
 53: 'CarName_dodge monaco (sw)',
 54: 'CarName_dodge rampage',
 55: 'CarName_honda accord',
 56: 'CarName_honda accord cvcc',
 57: 'CarName_honda accord lx',
 58: 'CarName_honda civic',
 59: 'CarName_honda civic (auto)',
 60: 'CarName_honda civic 1300',
 61: 'CarName_honda civic 1500 gl',
 62: 'CarName_honda civic cvcc',
 63: 'CarName_honda prelude',
 64: 'CarName_isuzu D-Max ',
 65: 'CarName_isuzu D-Max V-Cross',
 66: 'CarName_isuzu MU-X',
 67: 'CarName_jaguar xf',
 68: 'CarName_jaguar xj',
 69: 'CarName_jaguar xk',
 70: 'CarName_maxda glc deluxe',
 71: 'CarName_maxda rx3',
 72: 'CarName_mazda 626',
 73: 'CarName_mazda glc',
 74: 'CarName_mazda glc 4',
 75: 'CarName_mazda glc custom',
 76: 'CarName_mazda glc custom l',
 77: 'CarName_mazda glc deluxe',
 78: 'CarName_mazda rx-4',
 79: 'CarName_mazda rx-7 gs',
 80: 'CarName_mazda rx2 coupe',
 81: 'CarName_mercury cougar',
 82: 'CarName_mitsubishi g4',
 83: 'CarName_mitsubishi lancer',
 84: 'CarName_mitsubishi mirage',
 85: 'CarName_mitsubishi mirage g4',
 86: 'CarName_mitsubishi montero',
 87: 'CarName_mitsubishi outlander',
 88: 'CarName_mitsubishi pajero',
 89: 'CarName_nissan clipper',
 90: 'CarName_nissan dayz',
 91: 'CarName_nissan fuga',
 92: 'CarName_nissan gt-r',
 93: 'CarName_nissan juke',
 94: 'CarName_nissan kicks',
 95: 'CarName_nissan latio',
 96: 'CarName_nissan leaf',
 97: 'CarName_nissan note',
 98: 'CarName_nissan nv200',
 99: 'CarName_nissan otti',
 100: 'CarName_nissan rogue',
 101: 'CarName_nissan teana',
 102: 'CarName_nissan titan',
 103: 'CarName_peugeot 304',
 104: 'CarName_peugeot 504',
 105: 'CarName_peugeot 504 (sw)',
 106: 'CarName_peugeot 505s turbo diesel',
 107: 'CarName_peugeot 604sl',
 108: 'CarName_plymouth cricket',
 109: 'CarName_plymouth duster',
 110: 'CarName_plymouth fury gran sedan',
 111: 'CarName_plymouth fury iii',
 112: 'CarName_plymouth satellite custom (sw)',
 113: 'CarName_plymouth valiant',
 114: 'CarName_porcshce panamera',
 115: 'CarName_porsche boxter',
 116: 'CarName_porsche cayenne',
 117: 'CarName_porsche macan',
 118: 'CarName_renault 12tl',
 119: 'CarName_renault 5 gtl',
 120: 'CarName_saab 99e',
 121: 'CarName_saab 99gle',
 122: 'CarName_saab 99le',
 123: 'CarName_subaru',
 124: 'CarName_subaru baja',
 125: 'CarName_subaru brz',
 126: 'CarName_subaru dl',
 127: 'CarName_subaru r1',
 128: 'CarName_subaru r2',
 129: 'CarName_subaru trezia',
 130: 'CarName_subaru tribeca',
 131: 'CarName_toyota carina',
 132: 'CarName_toyota celica gt',
 133: 'CarName_toyota celica gt liftback',
 134: 'CarName_toyota corolla',
 135: 'CarName_toyota corolla 1200',
 136: 'CarName_toyota corolla 1600 (sw)',
 137: 'CarName_toyota corolla liftback',
 138: 'CarName_toyota corolla tercel',
 139: 'CarName_toyota corona',
 140: 'CarName_toyota corona hardtop',
 141: 'CarName_toyota corona liftback',
 142: 'CarName_toyota corona mark ii',
 143: 'CarName_toyota cressida',
 144: 'CarName_toyota mark ii',
 145: 'CarName_toyota starlet',
 146: 'CarName_toyota tercel',
 147: 'CarName_toyouta tercel',
 148: 'CarName_vokswagen rabbit',
 149: 'CarName_volkswagen 1131 deluxe sedan',
 150: 'CarName_volkswagen 411 (sw)',
 151: 'CarName_volkswagen dasher',
 152: 'CarName_volkswagen model 111',
 153: 'CarName_volkswagen rabbit',
 154: 'CarName_volkswagen rabbit custom',
 155: 'CarName_volkswagen super beetle',
 156: 'CarName_volkswagen type 3',
 157: 'CarName_volvo 144ea',
 158: 'CarName_volvo 145e (sw)',
 159: 'CarName_volvo 244dl',
 160: 'CarName_volvo 245',
 161: 'CarName_volvo 246',
 162: 'CarName_volvo 264gl',
 163: 'CarName_volvo diesel',
 164: 'CarName_vw dasher',
 165: 'CarName_vw rabbit',
 166: 'fueltype_diesel',
 167: 'fueltype_gas',
 168: 'aspiration_std',
 169: 'aspiration_turbo',
 170: 'doornumber_four',
 171: 'doornumber_two',
 172: 'carbody_convertible',
 173: 'carbody_hardtop',
 174: 'carbody_hatchback',
 175: 'carbody_sedan',
 176: 'carbody_wagon',
 177: 'drivewheel_4wd',
 178: 'drivewheel_fwd',
 179: 'drivewheel_rwd',
 180: 'enginelocation_front',
 181: 'enginelocation_rear',
 182: 'enginetype_dohc',
 183: 'enginetype_dohcv',
 184: 'enginetype_l',
 185: 'enginetype_ohc',
 186: 'enginetype_ohcf',
 187: 'enginetype_ohcv',
 188: 'enginetype_rotor',
 189: 'cylindernumber_eight',
 190: 'cylindernumber_five',
 191: 'cylindernumber_four',
 192: 'cylindernumber_six',
 193: 'cylindernumber_three',
 194: 'cylindernumber_twelve',
 195: 'cylindernumber_two',
 196: 'fuelsystem_1bbl',
 197: 'fuelsystem_2bbl',
 198: 'fuelsystem_4bbl',
 199: 'fuelsystem_idi',
 200: 'fuelsystem_mfi',
 201: 'fuelsystem_mpfi',
 202: 'fuelsystem_spdi',
 203: 'fuelsystem_spfi'}

In [ ]:
train_data

     wheelbase  carlength  ...  fuelsystem_spdi  fuelsystem_spfi
1         88.6      168.8  ...                0                0
2         94.5      171.2  ...                0                0
3         99.8      176.6  ...                0                0
4         99.4      176.6  ...                0                0
5         99.8      177.3  ...                0                0
..         ...        ...  ...              ...              ...
200      109.1      188.8  ...                0                0
201      109.1      188.8  ...                0                0
202      109.1      188.8  ...                0                0
203      109.1      188.8  ...                0                0
204      109.1      188.8  ...                0                0

[141 rows x 204 columns]

In [ ]:
mean = train_data.iloc[:,0:13].mean(axis=0) # taking the mean of 
train_data.iloc[:,0:13] -= mean
std = train_data.iloc[:,0:13].std(axis=0)
train_data.iloc[:,0:13] /= std
test_data.iloc[:,0:13] -= mean
test_data.iloc[:,0:13] /= std

In [ ]:
mean_label = train_label.mean()
train_label -= mean_label
std_label = train_label.std()
train_label /= std_label
test_label -= mean_label
test_label /= std_label

In [ ]:
print(mean_label)

13379.132390070921

In [ ]:
test_label

0      0.014148
10     0.372534
14     1.365880
15     2.122337
18    -1.004718
         ...
192    0.056886
193   -0.132991
194   -0.053621
196    0.318196
198    0.615529
Name: price, Length: 64, dtype: float64

In [ ]:
test = np.array(test_data.iloc[:])

In [ ]:
train = np.array(train_data.iloc[:])

In [ ]:
test_l= np.array(test_label.astype('float32'))

In [ ]:
train_l= np.array(train_label.astype('float32'))

In [ ]:
from keras import models
from keras import layers
def build_model(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,input_shape=(train.shape[1],)))
  model.add(layers.Dense(8, activation= act))
  model.add(layers.Dense(6, activation= act))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [ ]:
build_model('relu').summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 10)                2050
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 88
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 54
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7
=================================================================
Total params: 2,199
Trainable params: 2,199
Non-trainable params: 0
_________________________________________________________________

In [ ]:
build_model('tanh').summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 10)                2050
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 88
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 54
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 7
=================================================================
Total params: 2,199
Trainable params: 2,199
Non-trainable params: 0
_________________________________________________________________

In [ ]:
from keras import regularizers
def build_model_regular(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001),input_shape=(train.shape[1],)))
  model.add(layers.Dense(8, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001)))
  model.add(layers.Dense(6, activation= act,kernel_regularizer= regularizers.l1_l2(l1=0.001, l2=0.001)))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [ ]:
build_model_regular('tanh').summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_8 (Dense)              (None, 10)                2050
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 88
_________________________________________________________________
dense_10 (Dense)             (None, 6)                 54
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 7
=================================================================
Total params: 2,199
Trainable params: 2,199
Non-trainable params: 0
_________________________________________________________________

In [ ]:
from keras import regularizers
def build_model_drop(act):
  model = models.Sequential()
  model.add(layers.Dense(10, activation= act,input_shape=(train.shape[1],)))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(8, activation= act))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(6, activation= act))
  model.add(layers.Dropout(0.5))
  model.add(layers.Dense(1))
  model.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])
  return model

In [ ]:
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_relu = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_relu.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3

In [ ]:
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_tanh = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model('tanh')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_tanh.append(val_mae)

processing fold # 0
WARNING:tensorflow:5 out of the last 9 calls to <function Model.make_test_function.<locals>.test_function at 0x7f505203a200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 1
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5050e8a440> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 2
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f50586a3830> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f50532ce9e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [ ]:
#k-fold validtion with regularization
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_regular = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model_regular('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_regular.append(val_mae)

processing fold # 0
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f505864def0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 1
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f504fd46050> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 2
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5057ca3710> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5055557dd0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [ ]:
import numpy as np
k =  4
num_val_samples = len(train) // k
num_epochs = 100
all_scores_drop = []
for i in range(k):
  print('processing fold #', i)
  val_data = train[i * num_val_samples: (i + 1) * num_val_samples]
  val_targets = train_l[i * num_val_samples: (i + 1) * num_val_samples]
  partial_train_data = np.concatenate([train[:i * num_val_samples],train[(i + 1) * num_val_samples:]],  axis=0)
  # print(partial_train_data)
  partial_train_targets = np.concatenate([train_l[:i * num_val_samples],train_l[(i + 1) * num_val_samples:]],axis=0)
  model = build_model_drop('relu')
  model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
  val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
  all_scores_drop.append(val_mae)

processing fold # 0
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5052f59200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 1
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5055ec2b90> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 2
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f50543c6cb0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
processing fold # 3
WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f505864d4d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

In [ ]:
all_scores_relu

[0.3319145143032074,
 0.3411217927932739,
 0.43978264927864075,
 0.47449737787246704]

In [ ]:
all_scores_tanh

[0.35762208700180054,
 0.33443841338157654,
 0.42916521430015564,
 0.35493654012680054]

In [ ]:
all_scores_regular

[0.32402071356773376,
 0.24792218208312988,
 0.3320480287075043,
 0.34604498744010925]

In [ ]:
all_scores_drop

[0.6854559779167175,
 0.8160583972930908,
 0.49045267701148987,
 0.2925907373428345]

In [ ]:
model_tanh = build_model('tanh')
model_tanh.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_tanh.evaluate(test, test_l)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f5050e8c5f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 5ms/step - loss: 0.1349 - mae: 0.2796

In [ ]:
model_relu = build_model('relu')
model_relu.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

WARNING:tensorflow:6 out of the last 11 calls to <function Model.make_test_function.<locals>.test_function at 0x7f50520a3200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 5ms/step - loss: 0.1427 - mae: 0.2781

In [ ]:
model_regular = build_model_regular('relu')
model_regular.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

2/2 [==============================] - 0s 7ms/step - loss: 0.1427 - mae: 0.2781

In [ ]:
model_drop = build_model_drop('relu')
model_drop.fit(train, train_l,epochs= 80, batch_size=1, verbose=0)
test_mse_score, test_mae_score = model_relu.evaluate(test, test_l)

2/2 [==============================] - 0s 7ms/step - loss: 0.1427 - mae: 0.2781

In [ ]:
x_tanh = model_tanh.predict(test[5].reshape(1,test.shape[1]))

In [ ]:
x_tanh * std_label + mean_label

array([[7080.7393]], dtype=float32)

In [ ]:
x_relu = model_relu.predict(test[5].reshape(1,test.shape[1]))

In [ ]:
x_relu * std_label + mean_label

array([[6695.7275]], dtype=float32)

In [ ]:
x_regular = model_regular.predict(test[5].reshape(1,test.shape[1]))
x_regular * std_label + mean_label

array([[6563.041]], dtype=float32)

In [ ]:
x_drop = model_drop.predict(test[5].reshape(1,test.shape[1]))
x_drop * std_label + mean_label

array([[11522.983]], dtype=float32)

In [ ]:
test_l[5]* std_label + mean_label

7609.000199706916